### PR TITLE
Minor UI changes

### PR DESCRIPTION
**Pull request by fcduarte**
/cc @amitbharadwaj @josemontesdeoca

### CODE REVIEW

**Comment by josemontesdeoca** [comment]
LGTM :+1:

**Comment by josemontesdeoca** [comment]
@fcduarte , trying to run this version but the app crashes while opening up the Liquid asset view. Below stacktrace:

```
07-21 10:54:41.158: E/AndroidRuntime(5446): FATAL EXCEPTION: main
07-21 10:54:41.158: E/AndroidRuntime(5446): Process: org.missionassetfund.apps.android, PID: 5446
07-21 10:54:41.158: E/AndroidRuntime(5446): java.lang.NullPointerException
07-21 10:54:41.158: E/AndroidRuntime(5446):   at org.missionassetfund.apps.android.adapters.TransactionsExpandableListAdapter.getChildView(TransactionsExpandableListAdapter.java:112)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.AbsListView.obtainView(AbsListView.java:2255)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.ListView.onMeasure(ListView.java:1175)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.RelativeLayout.measureChild(RelativeLayout.java:689)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:473)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5137)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5137)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5137)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5137)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5137)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.View.measure(View.java:16537)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1942)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1132)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1321)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5725)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.Choreographer.doFrame(Choreographer.java:544)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.os.Handler.handleCallback(Handler.java:733)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.os.Handler.dispatchMessage(Handler.java:95)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.os.Looper.loop(Looper.java:136)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at android.app.ActivityThread.main(ActivityThread.java:5086)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at java.lang.reflect.Method.invokeNative(Native Method)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at java.lang.reflect.Method.invoke(Method.java:515)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
07-21 10:54:41.158: E/AndroidRuntime(5446):   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by fcduarte** [comment]
@josemontesdeoca the issues that you've filled are all related to data store on the server .. There are some transactions that doesn't contain a category. Is this field required or optional?

Anyway I'm going to put a null-safe check everywhere.

**Comment by josemontesdeoca** [comment]
LGTM.

**Pull request merged**
