### PR TITLE
Goal view - Save Goals to Parse

### PR DESCRIPTION
**Pull request by amitbharadwaj**
With date and frequency
@josemontesdeoca @fcduarte There's a change in GoalPaymenItnterval model.

### CODE REVIEW

**Comment by josemontesdeoca** [comment]
@amitbharadwaj added few comments. I think the major one is that GoalDetailsActivity should be ready to receive a goal that is passed along within the intent.

**Comment by amitbharadwaj** [comment]
@josemontesdeoca Yes. Flow from dashboardFragment to GoalDetailsActivity is yet to be done. For now I am querying parse in order to populate real data with views. It is temporary thing. 

datepicker: I did some research on date pickers. Didn't like any library as such. For now, I am using MM/dd/yyyy. Will get back to this in polish phase. 

I have put toast and error strings in strings.xml.

**Comment by josemontesdeoca** [comment]
@amitbharadwaj I am ok with querying from parse to populate real data. My point is the query hack should be added to dashboardFragment. GoalDetailsActivity should be shipped already listening to a goal from the intent passed as an extra. Else once the dashboard is code, GoalDetailsActivity would need to be refactor which does not make sense.

**Comment by amitbharadwaj** [comment]
@josemontesdeoca I did not want to change the DashBoardFragment as you would be working on it. I will add hooks from dashboard to goal details as a final step.

**Comment by josemontesdeoca** [comment]
@amitbharadwaj if you are up for two changes then I have no problems. I was thinking on just making life easy as I do not mind you changing DashboardFragment for the sake of testing the dependent activity. Any thoughts @fcduarte ?

**Comment by amitbharadwaj** [comment]
@josemontesdeoca yep. I will add hooks from dashboard to goals once goal and payment fields are stored and displayed well. It's not blocking anyway.

**Pull request merged**
