### PR TITLE
Goal view - Added goal payments adapter

### PR DESCRIPTION
**Pull request by amitbharadwaj**
@josemontesdeoca @fcduarte please review. 

 I somehow messed up last pull request. Few points to discuss:

I have changed amount columns to Double from Float. Parse seems to be more friendly with Double. 
I am create two packages: utils and adapters. 
Transaction seems to have a field called createdAt. Parse automatically adds createdAt field for all ParseObject. If we must need another separate field. Let's rename it to txnDate. I have commented out createdOut form Transaction for now.

### CODE REVIEW

**Comment by fcduarte** [comment]
I think we need another field for the transaction's date .. `createdAt` is an internal field for Parse which I  think they use for object synchronization (not 100% sure)

**Comment by josemontesdeoca** [comment]
Yes, we need to. I am working on the Adding transaction view and using createdAt for this would not work. We need to have our Own.

**Comment by fcduarte** [comment]
Also, on Parse we have `amount` and `amountInCents` for `transaction` class .. I don't know who defined this way but I suggest we use BigDecimal for our model and join the values .. I can do this change for my next pull request what do you guys think?

**Comment by amitbharadwaj** [comment]
Does Parse has getBigDecima()? I changed Float to Double in my branch.

**Comment by fcduarte** [comment]
No, it doesn't .. But we can code a getter/setter to solve this inside the model .. You can keep it Double I'll try to do that on my next PR.

**Comment by amitbharadwaj** [comment]
Okay. Can you guys review my PR and merge.

**Comment by fcduarte** [comment]
Reviewed. I'll merge it.

**Comment by amitbharadwaj** [comment]
Thanks Felipe.

**Pull request merged**
