### PR TITLE
Add missing enum properties to Goal model

### PR DESCRIPTION
**Pull request by josemontesdeoca**
more work towards polishing #5 

/cc @fcduarte @amitbharadwaj

### CODE REVIEW

**Comment by fcduarte** [comment]
Since the class is becoming bigger I think it makes sense to have a separated class for each enum.

**Comment by josemontesdeoca** [comment]
@fcduarte separation done. PTAL

**Comment by josemontesdeoca** [comment]
@fcduarte hope you can take a quick look to ship this in and get finished with the datamodel.

**Comment by fcduarte** [comment]
Sorry, I saw but forgot to comment .. :ship:

**Pull request merged**
